/* Generated by Together */

package com.dimata.harisma.entity.search;

public class SrcTraining {
    public long getDepartmentId(){ return departmentId; }

    public void setDepartmentId(long departmentId){ this.departmentId = departmentId; }

    public long getTrainingId(){ return trainingId; }

    public void setTrainingId(long trainingId){ this.trainingId = trainingId; }
    
    public long getTrainingType(){ return trainingType; }

    public void setTrainingType(long trainingType){ this.trainingType = trainingType; }

    public int getTypeOfSearch(){ return typeOfSearch; }

    public void setTypeOfSearch(int typeOfSearch){ this.typeOfSearch = typeOfSearch; }

    public int getSortBy(){ return sortBy; }

    public void setSortBy(int sortBy){ this.sortBy = sortBy; }

    /**
     * Getter for property trainingName.
     * @return Value of property trainingName.
     */
    public String getTrainingName() {
        return trainingName;
    }
    
    /**
     * Setter for property trainingName.
     * @param trainingName New value of property trainingName.
     */
    public void setTrainingName(String trainingName) {
        this.trainingName = trainingName;
    }
    
    private long departmentId;
    private long trainingId;
    private long trainingType;
    private int typeOfSearch;
    private int sortBy;
    private String trainingName = "";
    /* Update by Hendra Putu | 2016-01-06 */
    private long positionId = 0;
    private long divisionId = 0;

    /**
     * @return the positionId
     */
    public long getPositionId() {
        return positionId;
    }

    /**
     * @param positionId the positionId to set
     */
    public void setPositionId(long positionId) {
        this.positionId = positionId;
    }

    /**
     * @return the divisionId
     */
    public long getDivisionId() {
        return divisionId;
    }

    /**
     * @param divisionId the divisionId to set
     */
    public void setDivisionId(long divisionId) {
        this.divisionId = divisionId;
    }
}
